name: Book 2026-06-03 16:00
on:
  schedule:
    - cron: '57 12 1 6 *'
  workflow_dispatch: {}
jobs:
  book:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Book class
        env:
          ARBOX_EMAIL:              ${{ secrets.ARBOX_EMAIL }}
          ARBOX_PASSWORD:           ${{ secrets.ARBOX_PASSWORD }}
          ARBOX_WHITELABEL:         ${{ secrets.ARBOX_WHITELABEL }}
          ARBOX_BOXES_ID:           ${{ secrets.ARBOX_BOXES_ID }}
          ARBOX_LOCATIONS_BOX_ID:   ${{ secrets.ARBOX_LOCATIONS_BOX_ID }}
          ARBOX_MEMBERSHIP_USER_ID: ${{ secrets.ARBOX_MEMBERSHIP_USER_ID }}
        run: |
          python book_class.py \
            --class-date "2026-06-03" \
            --class-time "16:00" \
            --category-filter "W.O.D Hall A" \
            --wait-for-window
      - name: Remove this workflow
        if: always()
        run: |
          git config user.email "wc-signup-bot@users.noreply.github.com"
          git config user.name "WC Signup Bot"
          git rm .github/workflows/book-2026-06-03-1600.yml
          git commit -m "Done: 2026-06-03 16:00"
          git push
